[package]
name = "snarkos"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2021"

[workspace]
members = [
    "account",
    "cli",
    "display",
    "node",
    "node/consensus",
    "node/executor",
    "node/ledger",
    "node/messages",
    "node/rest",
    "node/router",
    "node/store"
]

[[bin]]
name = "snarkos"
path = "snarkos/main.rs"

[workspace.dependencies.snarkvm]
# path = "../snarkvm"
#git = "https://github.com/AleoHQ/snarkVM.git"
#rev = "7ac6eee"
version = "0.9.6"
features = ["circuit", "console", "parallel"]

[dependencies.anyhow]
version = "1"

[dependencies.clap]
version = "4.0"
features = ["derive"]

[dependencies.snarkos-account]
path = "./account"

[dependencies.snarkos-cli]
path = "./cli"

[dependencies.snarkos-display]
path = "./display"

[dependencies.snarkos-node]
path = "./node"

[dependencies.snarkos-node-consensus]
path = "./node/consensus"

[dependencies.snarkos-node-executor]
path = "./node/executor"

[dependencies.snarkos-node-ledger]
path = "./node/ledger"

[dependencies.snarkos-node-messages]
path = "./node/messages"

[dependencies.snarkos-node-rest]
path = "./node/rest"

[dependencies.snarkos-node-router]
path = "./node/router"

[dependencies.snarkos-node-store]
path = "./node/store"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[build-dependencies.walkdir]
version = "2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = true
